#!/bin/bash

usage()
{
  echo "Usage: $0 [ -h HOST:PORT:PASSWORD ] [ -i INVERVAL(sec) ] [ -o OUTPUT_FILE ]"
  exit 2
}

set_variable()
{
  local varname=$1
  shift
  if [ -z "${!varname}" ]; then
    eval "$varname=\"$@\""
  else
    echo "Error: $varname already set"
    usage
  fi
}

show_pools()
{
  local logfile=$1
  showpools | tee -a $logfile
}


#########################
# Main script starts here

unset OUTPUT_FILE

while getopts 'h:i:o:?' c
do
  case $c in
    h) set_variable HOST $OPTARG ;;
    i) set_variable INTERVAL $OPTARG ;;
    o) set_variable OUTPUT_FILE $OPTARG ;;
    ?) usage ;; esac
done

[ -z "$HOST" ] && [ -z "$OUTPUT_FILE" ] && [ -z "$INVERVAL" ] && usage

while true
do
  RESULT=`fsesexe -h $HOST -x "show calls count" | grep total. | cut -d ' ' -f 1`
  printf "`date +"%Y-%m-%d %H:%M:%S"`,$RESULT\n" | tee -a $OUTPUT_FILE
  sleep $INTERVAL
done



